In [210]:
import warnings
warnings.filterwarnings("ignore")

In [241]:
from bs4 import BeautifulSoup as bs
import regex as re

content = []
final_df = pd.DataFrame()

for filename in os.listdir("C:/Users/dsmiley/Documents/GitHub/iip-texts/epidoc-files")[2:]:
    filename = "C:/Users/dsmiley/Documents/GitHub/iip-texts/epidoc-files/" + filename
    # Read the XML file
    with open(filename, "r", encoding = "utf-8") as file:
        # Read each line in the file, readlines() returns a list of lines
        content = file.readlines()
        # Combine the lines in the list into a string
        content = "".join(content)
        bs_content = bs(content, "lxml")
        # Create dictionary
        # Creating content for pandas df
        # Name
        name = bs_content.find_all("idno")[1].text
        # Main Lang
        main_lang = bs_content.find("textlang").get("mainlang")
        # Ana
        ms_item = bs_content.find("msitem").get("ana")
        # Class
        try:
            ms_class = bs_content.find("msitem").get("class")[0]
        except:
            pass
        #else:
        #    ms_class = bs_content.find("msitem").get("class")[0]
        # Object_Desc
        obj_desc = bs_content.find("objectdesc").get("ana")
        # Support_Desc
        sup_desc = bs_content.find("supportdesc").get("ana")
        # Early Date
        try:
             late_date = bs_content.find("date").get("notafter")
        except:
            pass
        #late_date = bs_content.find("date").get("notafter")
        # After Date
        try:
             early_date = bs_content.find("date").get("notbefore")
        except:
            pass
        #early_date = bs_content.find("date").get("notbefore")
        # Period
        try:
             period = bs_content.find("date").get("period")
        except:
            pass
        #period = bs_content.find("date").get("period")
        # Region
        region = bs_content.find("region").getText()
        # Settlement
        settlement = bs_content.find("settlement").getText()
        # Geo_Place
        try:
             geo_place = bs_content.find("geogname").getText()
        except:
            pass
        #geo_place = bs_content.find("geogname").getText()

        sub_df = pd.DataFrame({"name":name, "main_lang":main_lang, "other_lang":other_lang,
                               "ms_item":ms_item, "ms_class":ms_class,"obj_desc":obj_desc,
                               "sup_desc":sup_desc, "early_date":early_date,"late_date":late_date,
                               "period":period, "region":region,"geo_type":geo_type,
                               "settlement":settlement, "geo_place":geo_place},
                              index=[0])

        final_df = pd.concat([final_df, sub_df])

In [326]:
final_df

,name,main_lang,other_lang,ms_item,ms_class,obj_desc,sup_desc,early_date,late_date,period,region,geo_type,settlement,geo_place
0,Abil 0001,arc,NaN,jewish,dedicatory,lintel,stone,70,500,Talmudic,Golan,site,Abilene,synagogue
0,Abur 0001,grc,NaN,christian,invocation,mosaic,NaN,300,700,Talmudic,Judaea,site,Bethennim,Church complex
0,Achz 0001,la,NaN,otherreligion,placemarkermilestone,milestonemarker,stone,83,83,http://n2t.net/ark:/99152/p0m63njbxb9,Coastal Plain,site,Achziv,
0,Aeri 0001,grc,NaN,otherreligion,dedicatory,slab,stone,96,169,http://n2t.net/ark:/99152/p0m63njtk9m,Syria,site,Aerita,
0,Aeri 0002,grc,NaN,otherreligion,dedicatory,slab,stone,96,169,http://n2t.net/ark:/99152/p0m63njtk9m,Syria,site,Aerita,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,Zoor 0459,arc,NaN,jewish,funeraryepitaph,tombstone,stoneother,429,429,http://n2t.net/ark:/99152/p0m63njjcn4,Negev,site,Zoora,An-naq' Cemetery
0,Zoor 0460,arc,NaN,jewish,funeraryepitaph,tombstone,stoneother,400,499,http://n2t.net/ark:/99152/p0m63njjcn4,Negev,site,Zoora,
0,Zoor 0461,grc,NaN,christian,funeraryepitaph,tombstone,limestone,503,503,http://n2t.net/ark:/99152/p0m63njjcn4,Negev,site,Zoora,
0,Zoor 0462,grc,NaN,christian,funeraryepitaph,tombstone,limestone,324,638,http://n2t.net/ark:/99152/p0m63njjcn4,Negev,site,Zoora,
0,Zoor 0463,arc,NaN,jewish,funeraryepitaph,tombstone,stoneother,429,429,http://n2t.net/ark:/99152/p0m63njjcn4,Negev,site,Zoora,

In [330]:
final_final_df = final_df[['name', 'main_lang', 'ms_item', 'ms_class', 'obj_desc','sup_desc', 'early_date', 'late_date', 'period', 'region', 'settlement', 'geo_place']]

final_final_df.to_csv('manuscript_data.csv', index=False)